# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jaswig
email: standup@jaswig.com
description: > # this means to ignore newlines until "baseurl:"
  Beautifully designed standing desk that is locally produced with high quality
  wood. This standup desk is perfect for at home or in your office
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jaswig.com" # the base hostname & protocol for your site
shopify_us: "http://us-store.jaswig.com"
shopify_eu: "http://eu-store.jaswig.com"

# Don't publish the shopify theme
exclude:
  - shopify-theme

# Build settings
markdown: kramdown

# Blog settings
excerpt_separator: <!--more-->

# Gem plugins
gems:
  - jekyll-sitemap
